app/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic.base import RedirectView
from django.views.static import serve
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

VERSION = 'v1'

schema_view = get_schema_view(
   openapi.Info(
      title="FixYourPlants API",
      default_version=VERSION,
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path(f'api/{VERSION}/', include('app.users.urls')),
    path(f'api/{VERSION}/', include('app.plants.urls')),
    path(f'api/{VERSION}/', include('app.sickness.urls')),
    path(f'api/{VERSION}/', include('app.diary.urls')),
    path(f'api/{VERSION}/', include('app.alerts.urls')),
    path(f'api/{VERSION}/', include('app.notification.urls')),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('simple/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # Redirección desde la raíz '/' a '/admin/'
   re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^$', RedirectView.as_view(url='/admin/', permanent=False)),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/users/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from app.users.views import ChangePasswordView, ConfirmEmailView, CreateUserView, CustomPasswordResetView, LoginView, \
    UserListView, UserDetailView, \
    UserUpdateView, LoggedInUserView, CustomPasswordSendedView, CustomPasswordSuccesView

router = SimpleRouter()

'''
USER
'''
router.register(r'users/list', UserListView, basename="user-list")
router.register(r'user', UserDetailView, basename="user-modify")
router.register(r'users', UserUpdateView, basename="user-update-destroy")
router.register(r'users/logged', LoggedInUserView, basename="user-logged")
router.register(r'create_user', CreateUserView, basename="user-create")

urlpatterns = [
    path('', include(router.urls)),
    path('password-reset/',CustomPasswordResetView.as_view(),name='request_password_reset'),
    path('password-sended/',CustomPasswordSendedView.as_view(),name='request_password_reset'),
    path('password-success/',CustomPasswordSuccesView.as_view(),name='request_password_reset'),
    path('change-password/<str:uidb64>/<str:token>/',ChangePasswordView.as_view() , name='change_password'),
    path('email-verified-success/<str:uidb64>/<str:token>/',ConfirmEmailView.as_view() , name='verification_success'),
    path('login/',LoginView.as_view({'post':'post'}),name='login'),
    ]

app/users/models.py
import uuid

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db.models import BooleanField, CharField, EmailField, TextField, UUIDField, ImageField
from django.db.models import ManyToManyField
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


class User(AbstractUser):
    # Attributes
    id = UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    image = ImageField(upload_to="users/", null=True, blank=True, default="users/default.png")
    about_me = TextField(null=True, blank=True, default='')
    email_verified = BooleanField(default=False)
    email = EmailField(unique=True)
    username = CharField(max_length=150, unique=True)
    googleAccount = BooleanField(default=False)

    # Relationships
    favourite_plant = ManyToManyField('plants.Plant', blank=True)
    affected_sicknesses = ManyToManyField('sickness.Sickness', blank=True)
    history = ManyToManyField('plants.History', blank=True)

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        try:
            # If updating the user, delete the old image if a new image is set
            old_user = User.objects.get(pk=self.pk)
            if old_user.image and old_user.image != self.image:
                old_user.image.delete(save=False)
        except User.DoesNotExist:
            pass  # User is new, so no old image to delete

        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # Delete the image when the user is deleted
        if self.image:
            self.image.delete(save=False)
        super().delete(*args, **kwargs)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

app/users/forms.py
# forms.py
from django import forms


class EmailForm(forms.Form):
    email = forms.EmailField(max_length=254,widget=forms.EmailInput(attrs={'placeholder': 'Correo Electrónico'}))
    
class NewPasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Nueva contraseña'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirmar Nueva Contraseña'}))

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        # Verificar que las contraseñas coincidan
        if password and confirm_password and password != confirm_password:
            self.add_error('password', 'Las contraseñas no coinciden.')
            self.add_error('confirm_password', 'Las contraseñas no coinciden.')

        # Verificar si la contraseña cumple con ciertos criterios (puedes personalizar esto)
        if password and len(password) < 8 and len(self.errors) == 0:
            self.add_error('password', 'La contraseña debe tener al menos 8 caracteres.')

        # Verificar si la contraseña es lo suficientemente fuerte según tus criterios
        if password and len(self.errors) == 0:
            if not any(char.isdigit() for char in password) and len(self.errors) == 0:
                self.add_error('password', 'La contraseña debe contener al menos un número.')

            elif not any(char.isupper() for char in password) and len(self.errors) == 0:
                self.add_error('password', 'La contraseña debe contener al menos una letra mayúscula.')

            elif not any(char.islower() for char in password) and len(self.errors) == 0:
                self.add_error('password', 'La contraseña debe contener al menos una letra minúscula.')

            elif not any(char in "!@#$%^&*()-_=+[]{}|;:'\",.<>?/" for char in password) and len(self.errors) == 0:
                self.add_error('password', 'La contraseña debe contener al menos un carácter especial.')

        return cleaned_data

app/users/views.py
from django.contrib.auth import authenticate, password_validation
from django.contrib.auth.tokens import default_token_generator
from django.core.exceptions import ValidationError as DjangoValidationError, ValidationError
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render, redirect
from django.template.loader import get_template
from django.urls import reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.views import View
from rest_framework import viewsets, mixins, status
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.response import Response
from rest_framework_simplejwt.tokens import RefreshToken

from app.config import common as settings
from app.users.forms import NewPasswordForm, EmailForm
from app.users.utils import get_user, validate_email
from .models import User
from .serializers import CreateUserSerializer, UserSerializer
from .swagger import user_list_swagger, user_detail_swagger, user_update_swagger, logged_in_user_swagger, \
    login_swagger, get_user_id_by_username_swagger, create_user_swagger


class UserListView(viewsets.GenericViewSet, mixins.ListModelMixin):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = (AllowAny,)
    pagination_class = None

    @user_list_swagger()
    def list(self, request, *args, **kwargs):
        return super().list(request, *args, **kwargs)

    @get_user_id_by_username_swagger()
    @action(detail=False, methods=['GET'])
    def get_user_id_by_username(self, request):
        username = request.query_params.get('username', None)
        if not username:
            return Response({'error': 'Username not provided'}, status=status.HTTP_400_BAD_REQUEST)

        try:
            user = User.objects.get(username=username)
            return Response({'user_id': user.id}, status=status.HTTP_200_OK)
        except User.DoesNotExist:
            return Response({'error': 'User not found'}, status=status.HTTP_404_NOT_FOUND)

class UserDetailView(viewsets.GenericViewSet, mixins.RetrieveModelMixin):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = (AllowAny,)
    pagination_class = None

    @user_detail_swagger()
    def retrieve(self, request, *args, **kwargs):
        return super().retrieve(request, *args, **kwargs)

class UserUpdateView(viewsets.GenericViewSet, mixins.UpdateModelMixin):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = (IsAuthenticated,)
    pagination_class = None

    @user_update_swagger()
    def update(self, request, *args, **kwargs):
        return super().update(request, *args, **kwargs)


class LoggedInUserView(viewsets.ViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = (IsAuthenticated,)

    @logged_in_user_swagger()
    @action(detail=False, methods=['GET'])
    def get_logged_in_user(self, request):
        user = request.user
        serializer = UserSerializer(user)
        return Response(serializer.data, status=status.HTTP_200_OK)
    
class CustomPasswordResetView(View):
    
    def get(self, request):
        form = EmailForm()
        return render(request, 'password_reset_form.html', {'form': form})
    
    def post(self, request):
        form = EmailForm(request.POST)
        if form.is_valid():
            user = User.objects.filter(email=form.cleaned_data['email']).first()
            if user != None:
                if validate_email(user.email):
                    token = default_token_generator.make_token(user)
                    uid = urlsafe_base64_encode(force_bytes(user.pk))
                    new_password_url = reverse('change_password', args=[uid, token])

                    template = get_template('password_reset_email.html')
                    content = template.render(
                        {'new_password_url': request.build_absolute_uri('/') + new_password_url[1:], 'username': user.username})
                    message = EmailMultiAlternatives(
                        'Cambio de contraseña',
                        content,
                        settings.Common.EMAIL_HOST_USER,
                        [user.email]
                    )

                    message.attach_alternative(content, 'text/html')
                    message.send()
                    return redirect('/api/v1/password-sended/')
            else:
                error_message = 'No se encontró un usuario con ese email.'
        return render(request, 'password_reset_form.html', {'form': form, 'error_message': error_message})

class ChangePasswordView(View):

    def get(self, request, uidb64, token):
        user = get_user(uidb64)
        if user is not None and default_token_generator.check_token(user, token):
            form = NewPasswordForm()
            return render(request, 'password_reset_confirm.html', {'form': form})
        else:
            return redirect('/?message=Error al cambiar la contraseña&status=Error')

    def post(self, request, uidb64, token):
        user = get_user(uidb64)
        if user is not None and default_token_generator.check_token(user, token):
            form = NewPasswordForm(request.POST)
            if form.is_valid():
                password = form.cleaned_data['password']
                password_validation.validate_password(password, user)

                user.set_password(password)
                user.save()
                return redirect('/api/v1/password-success/')
            return render(request, 'password_reset_confirm.html', {'form': form})
        return redirect('/?message=Error al cambiar la contraseña&status=Error')

    
class CustomPasswordSendedView(View):
    
    def get(self, request):
        return render(request, 'password_reset_sended.html')
    
class CustomPasswordSuccesView(View):
        
    def get(self, request):
        return render(request, 'password_reset_success.html')


class CreateUserView(viewsets.GenericViewSet, mixins.CreateModelMixin):
    queryset = User.objects.all()
    serializer_class = CreateUserSerializer
    permission_classes = (AllowAny,)
    pagination_class = None

    @create_user_swagger()
    def create(self, request, *args, **kwargs):
        print(request.data)
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        # Validación de la contraseña usando los validadores de Django
        password = serializer.validated_data.get('password')
        password_validation.validate_password(password, serializer.instance)

        user = serializer.save()

        username = serializer.validated_data.get('username')
        email = serializer.validated_data.get('email')

        try:
            if validate_email(email):
                token = default_token_generator.make_token(user)
                uid = urlsafe_base64_encode(force_bytes(user.pk))
                new_password_url = reverse('verification_success', args=[uid, token])

                template = get_template('verification_signup_email.html')
                content = template.render(
                    {'verification_url': request.build_absolute_uri('/') + new_password_url[1:], 'username': username})
                message = EmailMultiAlternatives(
                    'Verificación de Cuenta FixYourPlants',
                    content,
                    settings.Common.EMAIL_HOST_USER,
                    [request.data.get('email')]
                )
                message.attach_alternative(content, 'text/html')
                message.send()

            headers = self.get_success_headers(serializer.data)
            return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)
        
        except DjangoValidationError as e:
            error_data = {}
            for field, errors in e.error_dict.items():
                error_data[field] = errors[0]  # Assuming you want the first error message for each field
            return Response({'errors': error_data}, status=status.HTTP_400_BAD_REQUEST)



class ConfirmEmailView(View):
    
    def get(self, request, uidb64, token):
        user = get_user(uidb64)
        if user is not None and default_token_generator.check_token(user, token):
            user.email_verified = True
            user.save()
            print(user)
            return render(request, 'email_verification_success.html')
        else:
            return redirect('/docs/?message=Correo electrónico no verificado&status=Error')

class LoginView(viewsets.GenericViewSet):
    
    @login_swagger()
    def post(self, request):
        username = request.data.get('username')
        password = request.data.get('password')

    
        user = authenticate(username=username, password=password)
        
        if User.objects.filter(username=username).exists():
            user_models = User.objects.filter(username=username).first()
            if not user_models.email_verified:
                return Response({'email': 'El email no ha sido verificado'}, status=400)
        if user is None:
            return Response({'error': 'Usuario o contraseña incorrectos'}, status=401)
        
        refresh = RefreshToken.for_user(user)
        return Response({
            'refresh': str(refresh),
            'access': str(refresh.access_token),
            'userId': user.id,  # Aquí devolvemos el userID
            'message': 'Login successful'
        }, status=status.HTTP_200_OK)

app/users/templates/email_verification_success.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Verificación de Correo</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #e9f5e9;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            padding: 1em;
        }
        .container {
            background-color: #ffffff;
            padding: 4%;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            text-align: center;
            max-width: 40%;
            width: 100%;
        }
        h2 {
            color: #2e7d32;
            margin-top: 0;
        }
        p {
            color: #666;
            margin: 1em 0;
        }
        .plant-image {
            width: 50%;
            max-width: 200px;
            height: auto;
            margin-bottom: 1em;
            border-radius: 6px;
            border: 4px solid #4caf50;
        }
        @media (max-width: 600px) {
            .container {
                max-width: 90%;
                padding: 5%;
            }
            .plant-image {
                width: 70%;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <img src="https://i.kym-cdn.com/photos/images/newsfeed/002/449/283/0cf" alt="Plant Image" class="plant-image">
        <h2>Verificación de Correo</h2>
        <p>Su correo electrónico ha sido verificado correctamente. Ahora puede acceder a todas las funciones y beneficios de su cuenta.</p>
        <p>Por favor, asegúrese de mantener su información actualizada para disfrutar de una experiencia completa y personalizada en nuestra plataforma.</p>
        <p>Si tiene alguna duda o necesita asistencia, no dude en ponerse en contacto con nuestro soporte técnico.</p>
    </div>
</body>
</html>

app/users/templates/password_reset_confirm.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Establecer Nueva Contraseña</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #e9f5e9;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .container {
            background-color: #ffffff;
            padding: 4%;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            text-align: center;
            max-width: 80%; /* Ajustar el tamaño máximo del contenedor */
            width: 100%;
        }
        h2 {
            color: #2e7d32;
            margin-top: 0; /* Eliminar el margen superior de los encabezados */
        }
        p {
            margin-bottom: 1em; /* Añadir espacio después de los párrafos */
        }
        form {
            display: flex; /* Cambiar el contenedor del formulario a un flexbox */
            flex-direction: column; /* Establecer la dirección del flexbox a columna */
            align-items: center;
        }
        button {
            background-color: #4caf50;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
            margin-top: 1em; /* Añadir espacio sobre el botón */
        }
        button:hover {
            background-color: #388e3c;
        }
        .plant-image {
            width: 50%; /* Ajustar el tamaño de la imagen */
            max-width: 200px; /* Establecer un ancho máximo */
            height: auto; /* Hacer que la altura se ajuste automáticamente */
            margin-bottom: 1em; /* Añadir espacio debajo de la imagen */
            border-radius: 6px;
            border: 4px solid #4caf50;
        }
    </style>
</head>
<body>
    <div class="container">
        <img src="https://i.kym-cdn.com/photos/images/newsfeed/002/449/283/0cf" alt="Plant Image" class="plant-image">
        <h2>Establecer Nueva Contraseña</h2>
        <p>Ingrese su nueva contraseña para restablecer su cuenta.</p>
        <form method="post">
            {% csrf_token %}
            <label for="id_password">Contraseña:</label>
            <input type="password" id="id_password" name="password" class="custom-input" placeholder="Ingrese su contraseña">
            <label for="id_confirm_password" style="margin-top: 5px;">Confirmar Contraseña:</label>
            <input type="password" id="id_confirm_password" name="confirm_password" class="custom-input" placeholder="Confirme su contraseña">
            <button type="submit">Establecer Nueva Contraseña</button>
        </form>
    </div>
</body>
</html>

app/users/templates/password_reset_form.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restablecer Contraseña</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #e9f5e9;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .container {
            background-color: #ffffff;
            padding: 4%;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            text-align: center;
            max-width: 80%; /* Ajustar el tamaño máximo del contenedor */
            width: 100%;
        }
        h2 {
            color: #2e7d32;
            margin-top: 0; /* Eliminar el margen superior de los encabezados */
        }
        p {
            margin-bottom: 1em; /* Añadir espacio después de los párrafos */
        }
        form {
            margin-top: 2em; /* Añadir espacio entre el párrafo y el formulario */
        }
        button {
            background-color: #4caf50;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
            margin-top: 1em; /* Añadir espacio sobre el botón */
        }
        button:hover {
            background-color: #388e3c;
        }
        .plant-image {
            width: 50%; /* Ajustar el tamaño de la imagen */
            max-width: 200px; /* Establecer un ancho máximo */
            height: auto; /* Hacer que la altura se ajuste automáticamente */
            margin-bottom: 1em; /* Añadir espacio debajo de la imagen */
            border-radius: 6px;
            border: 4px solid #4caf50;
        }
        .error-message {
            color: #d32f2f;
            background-color: #f9d6d5;
            border: 1px solid #d32f2f;
            border-radius: 4px;
            padding: 10px;
            margin-bottom: 1em;       
        }
    </style>
</head>
<body>
    <div class="container">
        <img src="https://i.kym-cdn.com/photos/images/newsfeed/002/449/283/0cf" alt="Plant Image" class="plant-image">
        <h2>Restablecer Contraseña</h2>
        <p>Ingrese su nueva contraseña para restablecer su cuenta.</p>
        {% if error_message %}
            <div class="error-message">{{ error_message }}</div>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Restablecer Contraseña</button>
        </form>
    </div>
</body>
</html>

app/users/templates/password_reset_sended.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restablecimiento de Contraseña</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            display: flex;
            justify-content: center;
            align-items: flex-start;
            height: 100vh;
            margin: 0;
            padding-top: 50px; /* Espacio superior para posicionar el contenedor más arriba */
        }
        .container {
            background-color: #ffffff;
            padding: 30px; /* Aumentado el padding para hacer el contenedor más grande */
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
            max-width: 500px; /* Aumentado el max-width para hacer el contenedor más ancho */
            width: 100%;
        }
        h1 {
            color: #2e7d32;
        }
        p {
            color: #666;
        }
        a {
            color: #0066cc;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Correo Enviado</h1>
        <p>Le hemos enviado un correo a su cuenta de correo electrónico para restablecer su contraseña.</p>
        <p>Por favor, revise su bandeja de entrada y siga las instrucciones.</p>
    </div>
</body>
</html>

app/users/templates/password_reset_success.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cambio de Contraseña Exitoso</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            display: flex;
            justify-content: center;
            align-items: flex-start;
            height: 100vh;
            margin: 0;
            padding-top: 50px; /* Espacio superior para posicionar el contenedor más arriba */
        }
        .container {
            background-color: #ffffff;
            padding: 30px; /* Aumentado el padding para hacer el contenedor más grande */
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
            max-width: 500px; /* Aumentado el max-width para hacer el contenedor más ancho */
            width: 100%;
        }
        h1 {
            color: #2e7d32;
        }
        p {
            color: #666;
        }
        a {
            color: #0066cc;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Cambio de Contraseña Realizado</h1>
        <p>Su contraseña ha sido cambiada con éxito.</p>
        <p>Ahora puede iniciar sesión con su nueva contraseña.</p>
        <p>Ya puede cerrar esta pestaña.</p>
    </div>
</body>
</html>